### ISSUE TITLE
Bank Privatization

### ISSUE THREAD

**Issue by HaciGandalf** [booksaw/BetterTeams#151]
I am using a feature on my server. This feature is related to the fact that a certain amount of money disappears when players die. And I don't want players to keep their money in the team bank.

Features I want added:
- Completely disable team bank (true or false)
- Team bank money holding limit
- İncreased bank capacity when team levels up

(my English is not good. so sorry if i made mistakes)

**Comment by booksaw** [comment]
Team banks can be disabled already, through disabling the commands relating to them, this can be done in teampermissions.yml
The other two ideas will be added in the next update

**Comment by GuazP** [comment]
Just idea related to that what @HaciGandalf said. - I think it is evolution of his idea :)

It would be nice if there will be configuration if one team member kills another team member to actually stole from their bank some configurable flat or percent amount (if both: killed team have that amount in team bank, killers team bank could contain such quantity of money - otherwise go up to the cap).

**Comment by booksaw** [comment]
> Just idea related to that what @HaciGandalf said. - I think it is evolution of his idea :)
> 
> It would be nice if there will be configuration if one team member kills another team member to actually stole from their bank some configurable flat or percent amount (if both: killed team have that amount in team bank, killers team bank could contain such quantity of money - otherwise go up to the cap).

Please make a seperate feature request for me to look at this

**Comment by booksaw** [comment]
This feature has been implemented and will be included in the next update. Thank you for the sugggestion.
