### ISSUE TITLE
[FEATURE] Integration with KOTH

### ISSUE THREAD

**Issue by GuazP** [booksaw/BetterTeams#161]
**Is your feature request related to a problem? Please describe.**
I think it might encourage teams and populate activity of players to achieve greater goals together if their could compete as team in world events like King of the hill.

**Describe the solution you'd like**
I think integration to this plugin could bring great opportunity for team-based playing: https://www.spigotmc.org/resources/%E2%9C%85-king-of-the-hill-1-7-1-17-%E2%80%8D%E2%9C%85.6832/

**Describe alternatives you've considered**
Might be different plugin as target, but that one have support with a lot of team/faction based plugins, so it might be the best choice looking for downloads and reviews. 

**Additional context**
Doesn't apply.

**Comment by booksaw** [comment]
As listed on their plugin page they have hooks into many different plugins, for example Factions. 
As this plugin is a premium plugin I do not have access to it and I am not willing to spend money to get access to a premium plugin for development purposes.
I would suggest requesting the other plugin author added support for betterteams instead of the other way around, you can tell the other developer I am happy to answer any questions about betterteams that they have.

**Comment by GuazP** [comment]
Will do :)

**Comment by booksaw** [comment]
Due to the lack of activity and no outstanding queries, I am closing this issue.
