### ISSUE TITLE
[FEATURE] New Command Feature Request - '/teama purge'

### ISSUE THREAD

**Issue by BboyZeroOne** [booksaw/BetterTeams#21]
**Is your feature request related to a problem? Please describe.**
Feature Request. I would like to suggest a feature where admins could either manually purge player data with the command '/teama purge' or the plugin to automatically purge data on a set configuration of either daily/weekly/bi-weekly/monthly. 

**Describe the solution you'd like**
/teama purge - betterteams.admin.purge
/teama set purge <frequency>

Example Command Usage:
/teama set purge day - The data purge would be executed at the end of the day.
/teama set purge week - The data purge would be executed at the end of every week.
/teama set purge biweekly - The data purge would be executed at the end of every 14 days.
/teama set purge month - The data purge would be executed at the end of the month.

For plugin to automatically purge data, the config option example that admins could modify.
Example config:
##Day/Week/BiWeekly/Month
Purge Frequency: Month

**Describe alternatives you've considered**
None

**Additional context**
Additionally, before data is purged, the plugin could also reward the top teams/team members a configurable set of rewards. For example, the top 1 team would get $10,000 credited to their team bank, top 2 team would get $5,000, top 3 team would get 2,500 and so on. Rewards could be money/exp/items which is executed from a command or pre-configured rewards etc.

**Comment by booksaw** [comment]
Good idea. Though the scheduling for when purges run will be in the config as to do it, I would need to take a lot of details about the date which would just be annoying to do through commands.

**Comment by booksaw** [comment]
TODO list:

- [ ] add /teama purge with a confirm dialogue like /team disband. Purge should reset team score (not balance otherwise players would just withdraw money if they knew a purge was coming.
- [ ] add a config option to schedule purges (ie day of week / time) or (date in month / time) 
- [ ] For giving players rewards. I may either just point you to my plugin [chain command](https://www.spigotmc.org/resources/command-chain.36249/), though I have not tested it since 1.11 so I would need to do that. Or I will add it into better teams (this is still undecided) 
- [ ] Add placeholders for getting a team which is a certain rank in both score and balance

**Comment by booksaw** [comment]
This has been added for the next update.
