### ISSUE TITLE
Cannot create team [BUG]

### ISSUE THREAD

**Issue by wvbigdave** [booksaw/BetterTeams#25]
**Describe the bug**
/team create (team name) shows incorrect argument for command.  I have made sure that betterteams.create perm has been added to my LuckPerms config.  Saved and verified.  Readded and LuckPerms shows that no new changes were found.  Check perms and shows it is there.

**To Reproduce**
Steps to reproduce the behaviour:
- Run command /team create (team name)

**Expected behaviour**
Allows to create team.

**Screenshots**
![image](https://user-images.githubusercontent.com/45582061/90824890-15024280-e306-11ea-96b8-994c277f9a48.png)

**Details**
Please provide the following details about your server set-up:
- Paper version 1.16.1 build 136
- BetterTeams version 3.1.4

**Comment by booksaw** [comment]
A couple of questions

1. Do you get the same error with all better teams commands? For example if you run /team top does the same thing occur
2. This may be caused by my plugin conflicting with another plugin on your server, try running /betterteams:team create, do you get the same error? 

The reason I am leaning towards it being caused by a conflicting plugin on your server is because that message is not part of better teams so it should be impossible to be triggered by better teams.

**Comment by wvbigdave** [comment]
I am sorry, it was, thanks!
