### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ZeeceMC** [booksaw/BetterTeams#372]
### What is the bug?

Using placeholders, when without a team, the spacing isn't right for tags and in the tab menu.

### Expected Behaviour

Have better spacing when using placeholders

### How to Reproduce

1) Get TAB plugin, found on BitByBit (Mc Market)
2) Get better teams
3) Run them together

### Error message

No error message appears

### Output of /teama version

4.4.1

**Comment by booksaw** [comment]
I am unable to reproduce this issue. Check your configuration is the same as screenshotted below, then test the following command produces the same output as below `/papi parse me '%betterteams_name%'`. If the command produces the output below, and the issue is still occurring, the issue is with the tab plugin.
![image](https://user-images.githubusercontent.com/13976636/190187476-a7c005b2-7106-49ec-898d-ce513571cc1d.png)
![image](https://user-images.githubusercontent.com/13976636/190187559-5dd43ba0-60c8-44e7-b72b-e7b79df2f3eb.png)

**Comment by ZeeceMC** [comment]
I have no clue of what I did, but I can send you my configuration files for both the tab plugin and better teams, to see if anything went wrong there. 
[BetterTeams.zip](https://github.com/b
[TabList.zip](https://github.com/booksaw/BetterTeams/files/9570712/TabList.zip)
ooksaw/BetterTeams/files/9570711/BetterTeams.zip)

**Comment by booksaw** [comment]
When running `/papi parse me '%betterteams_name%'` what is printed in chat?

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
