### ISSUE TITLE
[BUG] Team Warp vanishes Bad Omen effect

### ISSUE THREAD

**Issue by rishabhk571** [booksaw/BetterTeams#446]
### What is the bug?

I got `Bad Omen` from pillager outpost, and `/team warp (raid)` to my raid farm , so that i could start the farm for xp totems and emeralds, but as soon as i warped, my bad omen vanished, and this has happened with everyone and all time. Warping vanishes bad omen effect

### Expected Behaviour

When I warped to my raid farm, `Bad Omen` should hv been there and raid should have started instead of effect vanish

### How to Reproduce

1. Go to Pillager Outpost & get Bad Omen
2. /team warp (point)
3. Bad Omen Vanishes

### Output of /teama version

[18:04:08 INFO]: [Helvetica] Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[18:04:08 INFO]: [Helvetica] Minecraft Version: git-Paper-448 (MC: 1.19.3)
[18:04:08 INFO]: [Helvetica] Language Selected: messages
[18:04:08 INFO]: [Helvetica] Current plugin version: 4.6.4

**Comment by booksaw** [comment]
@rishabhk571 I am unable to reproduce this bug (as shown in the before and after teleport screenshots), when I teleport using both `/team home` and `/team warp` I keep the bad omen effect. I ensured I got it naturally from killing a pillager rather than commands, if you could provide information on how to reproduce this bug from a clean server install it would be appreciated.

![image](https://github.com/booksaw/BetterTeams/assets/13976636/dff9508b-94c5-4204-b853-b337fd93f239)
![image](https://github.com/booksaw/BetterTeams/assets/13976636/0c941dfb-7d60-47b1-b712-1b7d20102ba2)

**Comment by rishabhk571** [comment]
I'll send a recording soon

**Comment by rishabhk571** [comment]
Closing this issue
Updating to `BetterTeams version 4.6.5`
Fixed!
