### ISSUE TITLE
[BUG] cant leave my team

### ISSUE THREAD

**Issue by Qx3l** [booksaw/BetterTeams#454]
### What is the bug?

It just keep saying
 Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose

Im not the owner of the group neither the admin

### Expected Behaviour

To  let me leave my team?

### How to Reproduce

/team leave
/team disband
/team kick

### Error message

Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose

### Output of /teama version

.

### Additional Information

.

**Comment by booksaw** [comment]
Hi please can you complete the bug report with the missing details:
* error message in the console when you try and leave the team
* a screenshot of the output of /teama version
Until this information is provided I cannot make any progress on the bug report

**Comment by booksaw** [comment]
The problem was fixed for @Millertym25 by setting `rebuildLookups` to true and restarting the server. @Qx3l could you try the same thing and let me know if this fixes the problem.

If the problem re-occurs after doing that please let me know even if setting `rebuildLookups` to true as the bug that is causing the error should be fixed.

**Comment by Yashraj46** [comment]
Same issue still facing @booksaw
