### ISSUE TITLE
Team Suffix instead of prefix

### ISSUE THREAD

**Issue by Susnug** [booksaw/BetterTeams#593]
### What is the feature request for?

Adding it so you can have the team name/tag a suffix, or a prefix, my server we have ranks, and those are prefix's, so there's not really a way for us to see what team someone is on in tab. (image is an example)
![Screenshot 2024-04-27 211625](https://github.com/booksaw/BetterTeams/assets/162061159/43441166-3e1b-4582-a347-05f811087b7c)

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand

**Comment by booksaw** [comment]
You will already be able to do that using placeholderAPI and a TAB management plugin which supports it. due to technical limitations with minecraft generally 2 plugins cannot interact with the tab menu at the same time. see the following wiki page for information. https://github.com/booksaw/BetterTeams/wiki/Managing-the-TAB-Menu

Let me know if you have any further questions, if you do not this ticket will be closed for inactivity in a month or so.

**Comment by booksaw** [comment]
This issue is being closed for inactivity. If you are still having problems feel free to open a new issue linking this one, make sure you answer any questions asked in the new issue.
