### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by reinsl** [booksaw/BetterTeams#594]
### What is the feature request for?

New Placeholder for Team Name at Specific Score Rank

### Additional Information

Could you add a placeholder to BetterTeams that allows users to retrieve the name of a team at a specific position in the score ranking? For example, "%betterteams_positionscore_{rank}_name%" would be extremely useful for displaying leaderboard information.

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [x] I understand

**Comment by Ceymikey** [comment]
This should already exist. The placeholder `%betterteams_position_name_1%` should return the name of the team that is first on score and this `%betterteams_position_score_1%` will reveal that teams score. Let me break it down.

%betterteams_position_name_1%

betterteams = Placeholder identifier
position = This is a position placeholder so served for leaderboards
name = This will show the name rather than other statistics like int score.
1 = Shows the best team the nr1 team (based of score

You can continue doing this by using
`%betterteams_position_name_2%`
`%betterteams_position_name_3%`
etc...

**Comment by booksaw** [comment]
As this already exists, I am going to close this issue.
