### ISSUE TITLE
[BUG] Server pauses when using /team info

### ISSUE THREAD

**Issue by Murmel-2** [booksaw/BetterTeams#608]
### What is the bug?

When using `/team info <random characters>` (`/team info aiosjdoidsjfiojfpiokgrgvioperjgrejoij`) it pauses the Server's Main Thread for a significant amount of time. This is because the entire command is running on the Main Thread of the Server and not on a different, async Thread to retreive the OfflinePlayer that doesn't exist. And because the OfflinePlayer doesn't exist, it will always continue to work, because it is not being cached. When spamming this command players are able to crash a server without any effort.

### Expected Behaviour

It should not pause the Server. Everything should continue as normal and the Team should be retreived on an async Thread.

### How to Reproduce

1. Run Command `/team info orifjhwoueishfuojshfuoishedf`
2. Watch the Server lag

### Output of /teama version

![image](https://github.com/booksaw/BetterTeams/assets/112826636/53edc40f-8af7-4a12-a931-17159cb69335)

**Comment by booksaw** [comment]
Where have you got this plugin download, the version listed in the screenshot does not exist?

**Comment by Murmel-2** [comment]
I have not downloaded this plugin myself, this is on a public Server called "ArmorUp". I got an admin of that server to do /teama version. They sent me that screenshot with the version

**Comment by booksaw** [comment]
Please could you ask your admins to download the latest version from the betterteams plugin page (see here: https://www.spigotmc.org/resources/better-teams.17129/ ) and check if the issue still continues because the info command should already be run asynchronously (see line 59: https://github.com/booksaw/BetterTeams/blob/af564e388a0201f67a2b3370a13d3bb32dfa98c7/src/main/java/com/booksaw/betterTeams/BooksawCommand.java#L59 )

**Comment by Murmel-2** [comment]
Alright, he updated it and it is fixed. I just didn't see the async call in the Command file ;p
