### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by KhrysAK47** [booksaw/BetterTeams#649]
### What is the bug?

/team kick does not work on offline players.

### Expected Behaviour

It should kick them normally even if they are offline. 

### How to Reproduce

1) Invite someone to a team.
2) Make them leave the server.
3) Try to kick them from the team.

### Output of /teama version

[08:55:01 INFO]: Storage Method: com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[08:55:01 INFO]: Minecraft Version: git-Paper-496 (MC: 1.20.4)
[08:55:01 INFO]: Language Selected: messages
[08:55:01 INFO]: Online mode: false
[08:55:01 INFO]: Player count: 79
[08:55:01 INFO]: Current plugin version: 4.9.4

**Comment by booksaw** [comment]
etterTeams allows offline players to be kicked and banned by default

This issue occurs often when you allow bedrock players to join your server, alternatively this can occur on some 'optimised' forks of paper such as pufferfish generally when the server is running in offline mode.

This occurs because BetterTeams uses UUIDs to store player information and in certain circumstances these UUIDs do not seem to be accurately returning player data when using the server configurations described above.

If you are able to find any reproducable steps from a fresh install of your server software / plugins, please add it to the following issue so I can notify the relevant developer about the issue. https://github.com/booksaw/BetterTeams/issues/489

NOTE: Using plugins like Geyser are not officially supported by BetterTeams and you will have to demonstrate any bugs you encounter while using that software are not caused by Geyser.

**Comment by KhrysAK47** [comment]
> etterTeams allows offline players to be kicked and banned by default
> 
> This issue occurs often when you allow bedrock players to join your server, alternatively this can occur on some 'optimised' forks of paper such as pufferfish generally when the server is running in offline mode.
> 
> This occurs because BetterTeams uses UUIDs to store player information and in certain circumstances these UUIDs do not seem to be accurately returning player data when using the server configurations described above.
> 
> If you are able to find any reproducable steps from a fresh install of your server software / plugins, please add it to the following issue so I can notify the relevant developer about the issue. #489
> 
> NOTE: Using plugins like Geyser are not officially supported by BetterTeams and you will have to demonstrate any bugs you encounter while using that software are not caused by Geyser.

We are running on Paper 1.20.4 and the player that cannot be kicked is not a Bedrock player.

**Comment by booksaw** [comment]
Yes, but I'm guessing you allow bedrock players to join, and plugins such as Geyser can interact with all UUIDs rather than just Bedrock players. 
Plus, your server is running in offline mode, which can also have inconsistent UUIDs (mainly on cracked accounts, but not always)

**Comment by KhrysAK47** [comment]
> Yes, but I'm guessing you allow bedrock players to join, and plugins such as Geyser can interact with all UUIDs rather than just Bedrock players. Plus, your server is running in offline mode, which can also have inconsistent UUIDs (mainly on cracked accounts, but not always)

If that is the case as you mention, it makes no sense that it sometimes allows to kick players if using their nickname in lowercase.
