### ISSUE TITLE
[FEATURE] '/team title'

### ISSUE THREAD

**Issue by BboyZeroOne** [booksaw/BetterTeams#8]
**Is your feature request related to a problem? Please describe.**
Its a feature request. To add '/team title', works similarly to factions '/f title'. Players can create their own custom titles with possibly color codes too.

**Describe the solution you'd like**
New Command:
/team title (title)                       -   betterteams.title (Default permission for team admin - Modify own title)
/team title (title) (player)          -   betterteams.title.others  (Default permission for team owner - Modify team member's title)
/teama title (title) (player)        -   betterteams.admin.title.others (For server admins to modify any player's title)
Access to use colored titles      -   betterteams.title.color.colorname
Access to use all colored titles -   betterteams.title.color.*

**Describe alternatives you've considered**
None

**Additional context**
Color titles permission should include all these.
![colors](https://user-images.githubusercontent.com/51330952/85828556-443f7c00-b7bb-11ea-9f7d-e4beb7cf2774.png)

**Comment by booksaw** [comment]
As I am not that familiar with the /f title. Can you confirm that it only shows within the faction info page, and nowhere else? 
Otherwise at what other points does the title show up?

**Comment by BboyZeroOne** [comment]
Yes, it only shows in the faction chat and not public chat. It also does show on ally chat.

Speaking of ally chat, we could also have ally for teams!

**Comment by booksaw** [comment]
Thanks. 
I will add /f title for version 3.0.9
Ally chat is a good idea. ill plan it out and add in the future (it may not be in the next update, it depends how much time I have)

**Comment by BboyZeroOne** [comment]
Gotcha! Looking forward to it! <3

**Comment by booksaw** [comment]
`/team title` and all associated commands will be included in version 3.0.9.
The suggestion of the command /team <title> for setting your own title has been kept, but the command has changed to `/title me <title>` to make the programming easier for no added complexity. 
I have slightly changed the permissions, instead of per colour permissions there are two permission nodes:
`betterteams.title.color.color` - Include colours in titles
`betterteams.title.color.format` - Include formatting colour codes within titles (for example bold and underline) 
An additional option will be added to the plugin config called maxTitleLength, this will limit the length of a title to ensure there are not 100 character long titles.

Finally @BboyZeroOne. I have created an additional [feature request](https://github.com/booksaw/BetterTeams/issues/9) for `/team ally`, if you have any thoughts could you add them to that feature request.
